snack-game/server

src/main/resources/application-local.yml, src/main/resources/application-production.yml
- resvoles: #15 
- ddl-auto=create
- data.sql 적용 시점 변경
- `defer-datasource-initialization: true`
=> fix: 기본 데이터가 입력되지 않는 문제

src/main/java/com/snackgame/server/applegame/controller/AppleGameController.java, src/main/java/com/snackgame/server/config/OpenApiConfig.java, src/main/java/com/snackgame/server/member/controller/GroupController.java, src/main/java/com/snackgame/server/member/controller/MemberController.java, src/main/resources/application.yml
=> refactor: API 문서 개선

build.gradle, src/main/java/com/snackgame/server/member/business/MemberService.java, src/main/java/com/snackgame/server/member/business/domain/Member.java, src/main/java/com/snackgame/server/member/controller/MemberController.java, src/main/java/com/snackgame/server/member/controller/dto/GroupRequest.java, src/main/java/com/snackgame/server/member/controller/dto/MemberRequest.java, src/main/java/com/snackgame/server/member/controller/dto/NameRequest.java, src/test/java/com/snackgame/server/member/business/MemberServiceTest.java
그룹 없이 사용자를 생성할 수 있다.
- resolves: #30 
배운점과 느낀점은 이슈에 기록되어 있다.
=> fix: 그룹 없이 사용자를 생성할 수 있다

.github/workflows/cd.yml, build.gradle, src/main/java/com/snackgame/server/common/domain/BaseEntity.java, src/main/resources/application-production.yml
=> feat: 프로덕션 환경에 DB를 연결한다

src/main/java/com/snackgame/server/config/WebMvcConfig.java
=> fix: CORS 설정을 특정 도메인으로 제한한다

src/main/java/com/snackgame/server/auth/BearerTokenExtractor.java, src/main/java/com/snackgame/server/auth/JwtMemberArgumentResolver.java, src/main/java/com/snackgame/server/config/WebMvcConfig.java, src/main/java/com/snackgame/server/member/controller/MemberController.java
=> rollback: 쿠키 관련 기능, CORS 설정은 유지

src/main/java/com/snackgame/server/applegame/dao/SessionRankingDao.java, src/test/java/com/snackgame/server/applegame/dao/SessionRankingDaoTest.java
- 공동2등이 2명이면 그 다음은 4등이다
그동안 dense_rank()를 잘못 알고있었다.
대신 rank()를 사용하고, 관련 테스트를 추가했다.
=> fix: dense_rank를 사용하지 않는다

src/main/java/com/snackgame/server/common/exception/GlobalExceptionHandler.java, src/main/java/com/snackgame/server/config/WebMvcConfig.java, src/main/resources/application.yml
=> feat: 루트 접근 시 서비스 메인으로 리다이렉션한다

src/main/java/com/snackgame/server/applegame/dao/SessionRankingDao.java, src/test/java/com/snackgame/server/applegame/dao/SessionRankingDaoTest.java
- 관련 테스트를 단일 유저로 하던 문제 개선
- 랭킹 가져오는 뷰를 코드상에서 표현
=> fix: 자신의 랭킹을 1등으로 가져오는 문제

src/main/java/com/snackgame/server/applegame/business/domain/AppleGame.java, src/test/java/com/snackgame/server/applegame/business/domain/AppleGameTest.java
=> chore: 게임판을 10*12 사이즈로 변경한다

src/main/java/com/snackgame/server/config/WebMvcConfig.java
=> chore: CORS 설정을 추가한다

.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, src/main/java/com/snackgame/server/rank/applegame/AppleGameRankingService.java, src/test/java/com/snackgame/server/applegame/AppleGameServiceTest.java, src/test/java/com/snackgame/server/rank/applegame/AppleGameRankingServiceTest.java
- resolves: #84 
이전에 랭킹에서 게스트 유저의 점수가 기록되던 문제를 해결하였습니다.
=> feat: 랭킹에서 게스트의 점수 노출을 제거한다

.github/workflows/cd.yml
=> feat: 배포 자동화를 무중단으로 개선한다

.github/workflows/cd.yml
배포 과정에 검증을 추가하였습니다.
그린 어플리케이션이 정상 실행되지 않으면, 변경사항을 반영하지 않고 배포를 종료합니다. (블루 어플리케이션 유지)
직접 머지해주세요!
=> feat(deploy): 그린 어플리케이션 실행 검증

.github/workflows/cd.yml
=> chore: 자동 배포 스크립트 개선

src/main/java/com/snackgame/server/config/WebMvcConfig.java
/(root) 페이지로 이동 시 "snackga.me"로 `redirect` 될 수 있도록 `viewController`를 설정해두었습니다.
AWS healthCheck를 위해서 `redirect`가 아닌 `ok`로 변경하였습니다.
=> refactor: AWS healthCheck를 위한 ViewController 수정

src/main/java/com/snackgame/server/rank/applegame/controller/dto/RankResponseV2.java, src/main/java/com/snackgame/server/rank/applegame/domain/BestScoreWithRankAndOwner.java, src/main/java/com/snackgame/server/rank/applegame/domain/BestScores.java, src/main/java/com/snackgame/server/rank/applegame/domain/Season.java, src/test/java/com/snackgame/server/rank/applegame/controller/AppleGameRankingControllerTest.java
1개 이상의 시즌 최고 점수가 있을 때, 자신의 기존 시즌 랭킹을 조회했을 때 오류가 발생하는 현상 
- 기존 시즌을 선택하면 2개의 랭킹이 선택됨
```sql
WITH best AS (select rank() over (order by score desc) as `rank`, score, owner_id
from best_score best
where score >= (
select score from best_score where owner_id = :ownerId and season_id = :seasonId
))
select best.rank, best.score,
m.id as owner_id, m.name as owner_name, mg.id as owner_group_id, mg.name as owner_group_name,
m.level as owner_level, m.profile_image as owner_profile_image
from best
inner join member m on m.id = best.owner_id
left join member_group mg on mg.id = m.group_id
where owner_id = :ownerId;
```
문제 해결 및 관련 테스트 보완
```sql
WITH best AS (select rank() over (order by score desc) as `rank`, score, owner_id
from best_score best
where season_id = :seasonId and score >= (
select score …
```
=> fix: 1개 이상의 시즌 최고 점수가 있어도 자신의 랭킹을 잘 표시한다

.github/workflows/dev-deploy.yml, .github/workflows/production-deploy.yml
문법상 오류, if문 반대로 적은 것 등 수정했습니다.
저엉말 쉽지않군요 ㄷㄷ
=> fix: 배포 스크립트의 오류를 수정한다

build.gradle
- #136 
기존에는 Spring Security에서 제공하는 `HttpSession`을 사용하여 소셜로그인을 진행하고 있었습니다.
`Spring Session`을 사용하도록 설정하여 JDBC를 통해 DB에 저장하는 방식으로 변경하였습니다.
---
일단은 앱 출시가 먼저이기에 여기까지 진행하고 백로그로 남겨두겠습니다.
=> refactor: 소셜로그인 세션 저장방식 변경

src/main/java/com/snackgame/server/applegame/AppleGameService.java, src/main/java/com/snackgame/server/applegame/controller/AppleGameControllerV2.java, src/main/java/com/snackgame/server/applegame/domain/game/AppleGame.java, src/main/java/com/snackgame/server/applegame/exception/ScoreDecreasingException.java, src/test/java/com/snackgame/server/applegame/domain/game/AppleGameTest.java
앱에서 사용하기 위해 임시로 점수를 직접 증가시킬 수 있는 기능을 추가합니다.
=> feat: 점수를 직접 증가시킨다

src/main/java/com/snackgame/server/rank/BestScoreRankingService.java, src/main/java/com/snackgame/server/rank/LegacyBestScoreRankingService.java, src/main/java/com/snackgame/server/rank/config/SeasonsInitializer.java, src/main/java/com/snackgame/server/rank/controller/RankingController.java, src/main/java/com/snackgame/server/rank/controller/dto/RankOwnerResponse.java, src/main/java/com/snackgame/server/rank/controller/dto/RankResponseV2.java, src/main/java/com/snackgame/server/rank/controller/dto/RankingResponse.java, src/main/java/com/snackgame/server/rank/dao/SessionRankingDao.java, src/main/java/com/snackgame/server/rank/dao/dto/RankingDto.java, src/main/java/com/snackgame/server/rank/domain/AppleGameBestScoreTransfer.java, src/main/java/com/snackgame/server/rank/domain/BestScore.java, src/main/java/com/snackgame/server/rank/domain/BestScoreWithRankAndOwner.java, src/main/java/com/snackgame/server/rank/domain/BestScores.java, src/main/java/com/snackgame/server/rank/domain/Season.java, src/main/java/com/snackgame/server/rank/domain/SeasonRepository.java, src/test/java/com/snackgame/server/fixture/BestScoreFixture.java, src/test/java/com/snackgame/server/fixture/SeasonFixture.java, src/test/java/com/snackgame/server/rank/BestScoreRankingServiceTest.java, src/test/java/com/snackgame/server/rank/controller/RankingControllerTest.java, src/test/java/com/snackgame/server/rank/dao/SessionRankingDaoTest.java, src/test/java/com/snackgame/server/rank/domain/BestScoresTest.java
작업 편의를 위해 API 스펙만 우선 변경하였음.
코드 상 스낵게임 종료 이벤트가 이미 발송되고 있으나, 받는 쪽이 아직임.
=> refactor(rank): 게임별로 랭킹을 조회하도록 API 스펙을 변경한다

src/main/java/com/snackgame/server/rank/provoke/ProvokeRepository.kt, src/main/java/com/snackgame/server/rank/provoke/ProvokeService.kt, src/test/java/com/snackgame/server/rank/provoke/ProvokeServiceTest.kt
=> 도발 시스템의 예외처리 추가

src/main/java/com/snackgame/server/rank/history/RankHistory.java, src/main/java/com/snackgame/server/rank/history/RankHistoryRenewal.java, src/test/java/com/snackgame/server/rank/provoke/ProvokeServiceTest.kt
RankHistory를 찾지 못하는 문제가 있었으나 해결하였습니다
=> RankHistory 관련 문제 해결

src/main/java/com/snackgame/server/game/snackgame/core/domain/item/policy/DailyGrantPolicy.kt, src/test/java/com/snackgame/server/game/snackgame/core/service/ItemServiceTest.kt
아이템 지급 시기가 "이전에 발급 받은 시간으로부터 1일 후" 였습니다.
사용자마다 달라져 혼란이 생길 수 있고 클라이언트와 맞추기 위해 매일 00시 기준 하루가 지나면 발급받을 수 있도록 수정하였습니다.
=> 아이템은 매일 00시 기준 한번 발급받을 수 있다
