snack-game/server

.deploy/runner.sh

```bash
PATH="/home/ubuntu/snackgame-server"
```
이렇게 하면 환경변수의 PATH가 오버라이딩 되어 sudo, java 등의 바이너리 위치를 찾을 수 없다.

실행 스크립트 오류 개선

---

.deploy/runner.sh

AS-IS:
```console
java -jar $APP_PATH/$JAR_NAME -DSpring.profiles.active=production
```
TO-BE:
```console
java -jar -DSpring.profiles.active=production $APP_PATH/$JAR_NAME
```
`-DSpring.profiles.active=production` 은 `-jar` 바로 뒤에 넣어야 한다. 
순서가 상관있다. 왜 이렇게 만들었는지 이유는 모르겠다. 🤷
[관련 Stackoverflow 질문](https://stackoverflow.com/a/37439625)

실행 스크립트 오류

---

build.gradle
src/main/java/com/snackgame/server/config/OpenApiConfig.java
src/main/resources/application.yml

문서의 정확성이 유지되는 한에서 가장 사용 비용(노동력)이 적은 방법을 선택할 것이다.
지난 프로젝트에서 Rest Docs를 사용해본 결과 문서화에 에너지가 너무 많이 소모되었다.
특히 문서화를 위한 반복 작업, '노동'이 가장 컸다.
이 점을 개선하기 위해 추가적인 API를 작성했다.
> ![](https://github.com/snack-game/server/assets/39221443/63526f97-e400-4a94-a6f5-fc59fd3a3eca)
> enum + `PayloadDocumentation.fieldWithPath` 을 활용했다.
> nested가 가능해 반복 작업을 줄이는 데는 큰 도움이 되었다.
하지만 이걸 팀 컨벤션으로 만드는 것도 어려울 것이라고 생각이 들었으며, 오히려 추후에 유지보수 비용이 커질 것이라고 생각했다.
그래서 협업 환경에서 사용하기엔 어려웠다.
또, 당시에 Rest Docs를 사용해야겠다고 생각한 장점들이 꼭 그렇지만도 않다는 것을 알게 되었다.
당시 동작을 테스트한 API만 문서화된다는 점으로 인해 다음과 같은 장점이 있다고 생각했다:
- 문서화를 빠뜨릴 확률이 적다.
- 항상 프로덕션 코드에 맞춰 최신으로 유지된다. (최신이 아니면 테스트가 실패한다)
하지만 이것은 Rest Docs만의 장점은 아니었다.
- Rest Docs를 사용해도 문서화를 빠뜨릴 수 있다. (문서화는 선택사항이다)
- 오히려 이 측면에서는 어노테이션 기반이 사용자 코드와 상호작용하므로 별다른 추가 코드 없이 문서화된다는 장점이 있다.
- 어노테이션 기반 문서화 라이브러리도 사용자 코드와 …

API 문서화 라이브러리 도입

---

src/main/java/com/snackgame/server/applegame/business/AppleGameService.java
src/main/java/com/snackgame/server/applegame/controller/AppleGameController.java
src/main/java/com/snackgame/server/applegame/controller/dto/CoordinateRequest.java
src/main/java/com/snackgame/server/applegame/controller/dto/MoveRequest.java
src/test/java/com/snackgame/server/applegame/business/AppleGameServiceTest.java

- resolves: #35 
클라이언트에서 한번에 여러 개의 수를 삽입할 수 있다.
'한 수'에 해당하는 좌표들만 입력할 수 있었다.
여러 수를 입력할 수 있게 된다.

feat: 세션에 여러개의 수를 삽입한다

---

src/main/java/com/snackgame/server/auth/BearerTokenExtractor.java
src/main/java/com/snackgame/server/auth/JwtMemberArgumentResolver.java
src/main/java/com/snackgame/server/common/exception/GlobalExceptionHandler.java
src/main/java/com/snackgame/server/member/controller/MemberController.java

JWT를 별도 응답으로 내려주는 대신 쿠키에 싣어 관리를 편하게 한다.
회원 등록 관련 API 스펙이 일부 변경된다.

feat: JWT를 쿠키에 싣는다

---

src/main/java/com/snackgame/server/applegame/business/domain/GameSessionTransferListener.java
src/main/java/com/snackgame/server/applegame/controller/AppleGameController.java
src/main/java/com/snackgame/server/applegame/controller/AppleGameControllerV2.java
src/main/java/com/snackgame/server/applegame/controller/AppleGameRankingController.java
src/main/java/com/snackgame/server/auth/jwt/FromToken.java
src/main/java/com/snackgame/server/auth/jwt/JwtMemberArgumentResolver.java
src/main/java/com/snackgame/server/auth/jwt/MemberResolver.java
src/main/java/com/snackgame/server/auth/oauth/support/SocialMemberSaver.java
src/main/java/com/snackgame/server/auth/oauth/support/SocialMemberSavingArgumentResolver.java
src/main/java/com/snackgame/server/config/OpenApiConfig.java
src/main/java/com/snackgame/server/config/WebMvcConfig.java
src/main/java/com/snackgame/server/member/business/MemberService.java
src/main/java/com/snackgame/server/member/business/domain/DistinctNaming.java
src/main/java/com/snackgame/server/member/business/domain/GuestNameRandomizer.java
src/main/java/com/snackgame/server/member/business/domain/MemberResolverImpl.java
src/main/java/com/snackgame/server/member/business/domain/Name.java
src/main/java/com/snackgame/server/member/business/domain/NameRandomizer.java
src/main/java/com/snackgame/server/member/business/domain/SocialMember.java
src/main/java/com/snackgame/server/member/business/domain/SocialMemberSaverImpl.java
src/main/java/com/snackgame/server/member/business/event/GameSessionTransferEvent.java
src/main/java/com/snackgame/server/member/controller/AuthController.java
src/main/java/com/snackgame/server/member/controller/MemberController.java
src/test/java/com/snackgame/server/member/business/MemberServiceTest.java
src/test/java/com/snackgame/server/member/business/domain/GuestNameRandomizerTest.java
src/test/java/com/snackgame/server/member/business/domain/NameTest.java

- resolves: #56 
소셜 로그인 시 중복 이름이 있으면 XX_2 , XX_3 과 같은 방식으로 숫자를 올려가며 해결한다.
하나의 도메인으로 만들었기 때문에 로직이 잘 보인다:
- resolves: #54 
(패키지 의존성이 한 방향으로 흐른다)
DI와 EventListener를 사용했다.
기존 auth 패키지 -> member 패키지에 접근하는 부분은 DI를 사용해 IoC 했다.
member 패키지 -> applegame 패키지에 접근하는 부분은 EventListener를 활용했다.
(잠만요.. EventListener도 IoC를 적용하는 방법 중 하나인 것 같네요?)
이제 패키지가 확실하게 분리되고 의존성이 한 방향으로 흐르게 되었으며, 작은 모듈로 분리할 수 있는 상태가 되었다.
가장 먼저 분리하고픈건 역시.. Spring Security를 활용한 부분이다.

중복 이름을 방지하고, 의존성 사이클을 제거한다

---

src/main/java/com/snackgame/server/auth/exception/AuthException.java
src/main/java/com/snackgame/server/auth/exception/InvalidTokenException.java
src/main/java/com/snackgame/server/auth/exception/OAuthAuthenticationException.java
src/main/java/com/snackgame/server/auth/exception/TokenAuthenticationException.java
src/main/java/com/snackgame/server/auth/exception/TokenExpiredException.java
src/main/java/com/snackgame/server/auth/exception/TokenInvalidException.java
src/main/java/com/snackgame/server/auth/exception/TokenUnresolvableException.java
src/main/java/com/snackgame/server/auth/token/util/JwtProvider.java
src/main/java/com/snackgame/server/common/exception/GlobalExceptionHandler.java
src/main/java/com/snackgame/server/common/exception/dto/ExceptionResponse.java

잘못된 토큰에 대한 구분이 없음  
조치 방법이 없음
잘못된 토큰을 두 가지로 구분 (만료, 유효하지 않음)  
조치 방법 명시 (`null`, `REISSUE`, `LOGOUT`)

refactor: 인증 예외 및 예외 응답 개선

---

src/main/java/com/snackgame/server/auth/token/TokenService.java
src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
src/main/java/com/snackgame/server/member/controller/AuthController.java
src/test/java/com/snackgame/server/auth/token/TokenServiceTest.java
src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java

원래는 엑세스 토큰만 사용하여 엑세스 토큰을 만료시키는 방식으로 로그아웃을 진행하였다.
하지만 리프레시 토큰이 생기고 리프레시 토큰을 만료시킬 방안이 필요했다.
로그아웃 API를 만들어 리프레시 토큰을 삭제(Soft-Delete)하고 
쿠키에서 리프레시 토큰을 제거하고 maxAge를 0으로 초기화하여 만료시키도록 하였다.

feat: 로그아웃 API를 추가한다

---

src/main/java/com/snackgame/server/member/MemberService.java
src/main/java/com/snackgame/server/member/controller/MemberController.java
src/main/resources/application-test.yml
src/test/java/com/snackgame/server/applegame/AppleGameServiceTest.java
src/test/java/com/snackgame/server/applegame/domain/game/AppleGamesTest.java
src/test/java/com/snackgame/server/auth/token/TokenServiceTest.java
src/test/java/com/snackgame/server/member/GroupServiceTest.java
src/test/java/com/snackgame/server/member/MemberServiceTest.java
src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java
src/test/java/com/snackgame/server/member/domain/MemberRepositoryTest.java
src/test/java/com/snackgame/server/member/fixture/MemberFixture.java
src/test/java/com/snackgame/server/rank/applegame/AppleGameRankingServiceTest.java
src/test/java/com/snackgame/server/rank/applegame/dao/SessionRankingDaoTest.java
src/test/java/com/snackgame/server/rank/applegame/domain/BestScoresTest.java
src/test/java/com/snackgame/server/support/database/CleanDatabaseBeforeEach.java
src/test/java/com/snackgame/server/support/database/DatabaseCleaner.java
src/test/java/com/snackgame/server/support/database/DatabaseCleaning.java
src/test/java/com/snackgame/server/support/general/DatabaseCleaningDataJpaTest.java
src/test/java/com/snackgame/server/support/general/ServiceTest.java
src/test/java/com/snackgame/server/support/restassured/RestAssuredTest.java
src/test/java/com/snackgame/server/support/restassured/SetupRestAssuredPort.java

- resolves: #78
테스트 개선 및 앞으로 테스트 추가를 위한 기반작업을 한다.
- 각종 테스트에 트랜잭션 롤백을 위한 `@Transactional` 사용
- 테스트 메서드 자체에 트랜잭션이 적용되어 실제 환경과 다른 테스트가 진행될 가능성이 높음.
- 어플리케이션 컨텍스트 초기화 및 DB 재설정을 위해 `@DirtiesContext` 사용
- 지금까지 `@Transactional`을 사용할 수 없는 경우에 대신 사용하였음
- 연속적으로 테스트가 진행되는 경우 트랜잭션이 닫히지 않아 기아 현상 발생
- `MemberFixture`를 저장한 후 `EntityManager`를 닫지 않아서 발생한 문제
- RestAssured를 사용한 인수 테스트 진행 시 필요한 복잡한 설정 과정 필요
- JUnit Extension `BeforeEachCallback`사용, DB Truncate 자동화
- `@DatabaseCleaning` 어노테이션 도입
- 트랜잭션 롤백을 위해 사용하던 `@Transactional`, 어플리케이션 컨텍스트 초기화를 위해 사용하던 `@DirtiesContext` 제거
- `@DatabaseCleaningDataJpaTest``@ServiceTest` 사용 가능
- RestAssured 테스트 설정 자동화
- `@RestAssuredTest` 사용 가능

refactor(test): 테스트와 그 기반 코드를 보완한다

---

src/main/resources/application-production.yml

(는 아니고 관련 커멘트입니다. 열심히 작성했으니 한 번 읽어봐주세용)
- https://github.com/snack-game/server/pull/91#discussion_r1464700026
- ddl-auto가 update로 설정되어 있었음
- DDL 문제로 런타임 중 오류 발생 가능성이 있었음.
- 어플리케이션이 사용하는 DB 계정은 어차피 권한이 없어 DDL 수정이 불가함.
- ddl-auto를 validate로 설정한다
- 어플리케이션 실행 시점에 DDL을 검증한다.
- 문제가 있으면 배포가 취소되므로 한층 안전해졌음.

chore: 프로덕션의 ddl-auto 설정을 validate로 변경

---

src/main/java/com/snackgame/server/auth/token/TokenService.java
src/main/java/com/snackgame/server/auth/token/dto/TokenDto.java
src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
src/main/java/com/snackgame/server/member/controller/AuthController.java
src/test/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolverTest.java
src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java

[노션 페이지](https://jumbled-droplet-70f.notion.site/49fde1b1292048b09d755c6629a1b6e8?pvs=4)에 제가 고민한 내용들을 먼저 적어두었는데, 정환님도 함께 고민해보고 글을 완성시켜주셨으면 좋겠어요!
특히 다음 측면을 고려하면서 진행해보면 성장이 있을 것 같습니다 🚀:
- '서버 배포와 클라이언트 배포의 시간적 순서'
- '어떻게 클라이언트 개발자들이 대응할 때까지 시간을 벌어줄 수 있을까?' 
토큰을 Response Body에 싣어 응답하고, 클라이언트에서 직접 관리하였다.
과도기: 토큰을 Response Body와 쿠키 모두에 싣어 응답한다.
클라이언트 배포 이후: 모든 토큰을 완전히 쿠키로 이관한다.

refactor: 액세스 토큰을 쿠키로 이관한다

---

.github/workflows/cd.yml
build.gradle
src/main/java/com/snackgame/server/applegame/controller/AppleGameControllerV2Docs.java
src/main/java/com/snackgame/server/auth/oauth/config/OAuthConfig.java
src/main/java/com/snackgame/server/auth/token/JwtProviderConfig.java
src/main/java/com/snackgame/server/auth/token/TokenService.java
src/main/java/com/snackgame/server/auth/token/dto/TokensDto.java
src/main/java/com/snackgame/server/auth/token/support/TokenToCookies.java
src/main/java/com/snackgame/server/auth/token/support/TokensFromCookie.java
src/main/java/com/snackgame/server/auth/token/support/TokensResolver.java
src/main/java/com/snackgame/server/auth/token/util/JwtProvider.java
src/main/java/com/snackgame/server/auth/token/util/KeyLocator.java
src/main/java/com/snackgame/server/config/OpenApiConfig.java
src/main/java/com/snackgame/server/config/WebMvcConfig.java
src/main/java/com/snackgame/server/member/controller/AuthController.java
src/main/java/com/snackgame/server/member/controller/MemberController.java
src/main/java/com/snackgame/server/member/controller/dto/GroupResponse.java
src/main/java/com/snackgame/server/member/controller/dto/MemberDetailsResponse.java
src/main/java/com/snackgame/server/member/controller/dto/MemberDetailsWithTokenResponse.java
src/main/java/com/snackgame/server/member/controller/dto/MemberRequest.java
src/main/java/com/snackgame/server/member/controller/dto/NameRequest.java
src/main/resources/application-local.yml
src/main/resources/application-production.yml
src/main/resources/application-test.yml
src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java

- #97
액세스 토큰의 쿠키 maxAge가 너무 짧은 관계로 만료 여부를 서버가 구분해 줄 수 없었음.
액세스 토큰의 쿠키 maxAge를 리프레시 토큰만큼 연장
관련한 예외 응답 문서화
- '일' 기준 Expiry 설정(헷갈리지 않도록)
- 환경 변수 이름 변경 및 오래된 토큰 secret 변경

fix: 토큰 기간 연장 및 관련 문서화 작업

---

src/main/java/com/snackgame/server/rank/applegame/domain/AppleGameBestScoreTransfer.java

- #99 
1. 게스트 점수와 소셜 계정 점수의 비교가 반대로 되어있었다.
2. 점수 통합 과정에서 소셜 계정 점수를 삭제하지 않아 `Best Score`가 두개 생길 수 있었다.
1. 점수 비교 순서 변경
2. 소셜 계정 점수를 삭제해주는 과정을 추가하였다.

fix: 게스트와 소셜 계정 점수 통합 버그 수정

---

src/main/java/com/snackgame/server/member/controller/dto/StatusResponse.java
src/main/java/com/snackgame/server/member/domain/Status.java
src/test/java/com/snackgame/server/member/domain/StatusTest.java

- [FE PR] https://github.com/snack-game/front/pull/148#discussion_r1501771088
현재 레벨의 최대 경험치를 내부적으로만 사용했다.
최대 경험치도 응답에 싣는다.

feat: 현재 레벨의 최대경험치를 알 수 있다

---

.github/workflows/ci.yml
build.gradle
src/main/java/com/snackgame/server/common/file/ResourceResolver.kt
src/main/java/com/snackgame/server/common/file/S3FileUploader.kt
src/main/java/com/snackgame/server/config/S3Config.java
src/main/java/com/snackgame/server/member/MemberAccountService.java
src/main/java/com/snackgame/server/member/controller/MemberController.java
src/main/java/com/snackgame/server/member/controller/dto/MemberDetailsResponse.java
src/main/java/com/snackgame/server/member/domain/Guest.java
src/main/java/com/snackgame/server/member/domain/Member.java
src/main/java/com/snackgame/server/member/domain/ProfileImage.java
src/main/java/com/snackgame/server/member/domain/SnackgameSocialMemberSaver.java
src/main/java/com/snackgame/server/member/domain/SocialMember.java
src/main/java/com/snackgame/server/member/domain/Status.java
src/main/java/com/snackgame/server/member/exception/InvalidProfileImageException.java
src/main/resources/application.yml
src/test/java/com/snackgame/server/member/MemberAccountServiceTest.java
src/test/java/com/snackgame/server/member/domain/GuestTest.java
src/test/java/com/snackgame/server/member/domain/ProfileImageTest.java
src/test/java/com/snackgame/server/member/fixture/MemberFixture.java

**커밋 수가 많지 않으니 [여기](https://github.com/snack-game/server/pull/109/commits/4fe7b1e7ab089bbba76fc6bd1544f00fccdb6d32)부터 커밋별로 보시는 것을 추천합니다**
`Next >` 를 눌러 넘길 수 있어용
- 소셜 로그인 시 프로필 이미지를 일부 저장하였으나 사용하지 않았다.
- 계정 생성시 기본 프로필 이미지가 할당된다.
- <img src="https://snackgame.s3.ap-northeast-2.amazonaws.com/static/logo.png" width=50>
- 프로필 이미지를 원하는 이미지로 변경할 수 있다.
- '사용자 소셜 계정으로 통합'시 토큰이 변경되지 않는 이슈(쿠키 토큰 미대응)
- `Status` 객체를 외부에서 생성해 넣어주었다.
- '소셜 계정으로 통합'시 새로운 유저로 쿠키 토큰을 재발급한다.
- Member 객체 내부에서 Status 객체를 생성하고, 재할당을 막아 외부에서 조작되지 않도록 개선한다.

feat: 프로필 이미지를 추가한다

---

src/main/java/com/snackgame/server/config/S3Config.java

- #109 
운영 환경과 개발 환경에서 S3 설정을 다르게 하고자 함.
그러나 `@Profile`을 적절히 사용하지 못해서 중복된 Bean이 발생했음.
프로덕션과 / 프로덕션이 아닌 상황으로 구분해 빈을 생성하도록 수정

fix: 개발 환경과 운영 환경 S3 credential 분리

---

src/main/java/com/snackgame/server/common/file/S3FileUploader.kt
src/main/java/com/snackgame/server/member/domain/Member.java
src/main/java/com/snackgame/server/member/domain/ProfileImage.java
src/main/java/com/snackgame/server/member/domain/SnackgameSocialMemberSaver.java
src/main/java/com/snackgame/server/member/domain/SocialMember.java
src/test/java/com/snackgame/server/common/file/S3FileUploaderTest.kt
src/test/java/com/snackgame/server/member/fixture/MemberFixture.java

[커밋 별로 리뷰](https://github.com/snack-game/server/pull/115/commits/a39ca0dac13b34ce8c5c047c80e8420cb85b8cfd)하시는 걸 추천합니다!
변경한 프로필 이미지가 소셜 로그인을 다시 했을 때 갱신되었다.
S3 업로드할 파일 이름을 생성하는 과정에 원본 파일의 이름이 포함되어, 최종 URL이 너무 길어지는 경우가 발생했다.
소셜 로그인 시 소셜 이미지가 갱신되지 않도록 변경한다.
업로드할 파일 이름 지정 방식을 UUID와 `String.hashCode()`를 사용하도록 변경하였다.
----
매끄러운 협업을 위해 우선 머지합니다!

refactor: 프로필 이미지 갱신 시기와 네이밍 방식을 개선한다

---

.github/workflows/cd.yml
src/main/java/com/snackgame/server/test/TestController.java
src/main/resources/application.yml

- #116 
- resolves: #116 
오래된 버전의 애플리케이션을 종료할때 진행 중인 요청이 존재하면 그 요청을 처리하지 않고 강제 종료를 하였다.
Graceful Shutdown을 적용하여 새로운 요청은 차단하고 진행 중인 요청은 완료 후 정상 종료를 하도록 변경하였다.

chore: Graceful Shutdown 적용

---

src/main/java/com/snackgame/server/applegame/AppleGameService.java
src/main/java/com/snackgame/server/applegame/controller/dto/GameResultResponse.java
src/main/java/com/snackgame/server/applegame/domain/game/AppleGames.java
src/main/java/com/snackgame/server/applegame/domain/game/Percentile.java
src/main/java/com/snackgame/server/applegame/exception/AppleGameException.java
src/main/java/com/snackgame/server/applegame/exception/InaccuratePercentileException.java
src/main/java/com/snackgame/server/applegame/exception/SessionNotFinishedException.java
src/main/java/com/snackgame/server/common/exception/BusinessException.java
src/main/java/com/snackgame/server/common/exception/GlobalExceptionHandler.java
src/main/java/com/snackgame/server/common/exception/Kind.java
src/main/java/com/snackgame/server/common/exception/dto/ExceptionResponse.java
src/test/java/com/snackgame/server/applegame/AppleGameServiceTest.java
src/test/java/com/snackgame/server/applegame/domain/game/PercentileTest.java

게임 완료 시 응답이 없었으며, 클라이언트가 아는 정보로 처리하였다.
비즈니스 예외의 상태 코드를 제어할 수 없었다.
게임 완료 시 점수 및 백분위를 퍼센트로 함께 반환한다.
비즈니스 예외의 '종류'를 통해 상태 코드 및 로그 여부를 제어할 수 있다.

feat: 게임 종료시 점수와 백분위를 알 수 있다

---

src/main/java/com/snackgame/server/common/file/S3FileUploader.kt

(엄청 간단한 변경사항입니다)
- 파일 객체 자체의 해시를 사용하였다.
우리는 현재 Spring Resource 중 MultipartFileResource 및 UrlResource를 주로 사용하고 있다.
(사진참고)
그러나 `MultipartFileResource`의 `hashCode()`는 별도로 재정의되어있지 않아, 재활용되는 경우 같은 해시코드가 나올 가능성이 있다.
이 경우 해시와 UUID를 병합하여 파일명을 짓는 것으로 충돌 가능성을 극도로 낮춘다는 의도를 온전히 표현하지 못한 셈이다.
파일명을 해시하도록 수정

fix(file): 파일 객체의 해시가 아닌 파일 이름의 해시를 이용한다

---

src/main/java/com/snackgame/server/applegame/domain/game/AppleGame.java
src/test/java/com/snackgame/server/applegame/domain/game/AppleGameTest.java
src/test/java/com/snackgame/server/history/dao/GameHistoryDaoTest.java

- resolves: #123 
- 게임의 종료 시간을 지정할 수 없었으며 DB를 update 해야만 게임의 종료를 확정시킬 수 있었다. 
- 게임의 종료 시간을 생성과 동시에 지정해둔다.
---
- #50 
이 이슈는 `종료 시간`을 지정해두어도 근본적으로 방지할 수가 없어 추후에 다른 방법을 찾아보겠습니다.
1. 기존 `isFinished`보다 더 정확한 지표로 사용할 수 있습니다.
2. 테스트의 유연성이 커집니다.

refactor: AppleGame의 종료시간을 지정해두도록 추가한다

---

src/test/java/com/snackgame/server/history/dao/GameHistoryDaoTest.java

테스트이름이 테스트의 목적과 차이가 있었습니다.
테스트이름을 목적에 맞춰 더 명확히 변경하였습니다.
---
추가사항
- 전적 조회 데이터를 최신순으로 주려하다가 '최근 25게임'을 최신순으로 주는 것이 생각보다 복잡하여 프론트와 협의 후 클라이언트에서 처리하기로 합의했습니다.

test: 테스트이름 수정

---

src/main/java/com/snackgame/server/game/session/domain/Session.kt
src/main/java/com/snackgame/server/game/snackgame/domain/Snackgame.kt
src/main/java/com/snackgame/server/game/snackgame/service/SnackgameService.kt
src/test/java/com/snackgame/server/game/session/domain/SessionTest.kt

문법 상 어디서든 점수 수정이 가능했음
세션을 상속하는 객체 내에서만 점수 수정이 가능하게 하였음.
현재 스낵게임의 경우는 임시로 점수 수정 메서드를 열어두었음. (`@Deprecated` 표시)

refactor(session): 점수를 직접적으로 수정할 수 없다

---

src/main/java/com/snackgame/server/applegame/controller/AppleGameControllerV2.java
src/main/java/com/snackgame/server/applegame/controller/AppleGameControllerV2Docs.java
src/main/java/com/snackgame/server/config/OpenApiConfig.java
src/main/java/com/snackgame/server/game/metadata/Metadata.kt
src/main/java/com/snackgame/server/game/metadata/MetadataController.kt
src/main/java/com/snackgame/server/game/metadata/MetadataResponse.kt
src/main/java/com/snackgame/server/game/session/domain/Session.kt
src/main/java/com/snackgame/server/game/session/event/SessionEndEvent.kt
src/main/java/com/snackgame/server/game/session/service/dto/SessionResponse.kt
src/main/java/com/snackgame/server/game/snackgame/controller/SnackgameController.kt
src/main/java/com/snackgame/server/game/snackgame/domain/Snackgame.kt
src/main/java/com/snackgame/server/game/snackgame/domain/SnackgameRepository.kt
src/main/java/com/snackgame/server/game/snackgame/service/SnackgameService.kt
src/main/java/com/snackgame/server/game/snackgame/service/dto/SnackgameEndResponse.kt
src/main/java/com/snackgame/server/member/domain/Member.java

게임 종료 시 기존 사과게임에서 보이던 백분율이 없었음.
- API 문서를 분리하였음. (특히 지원 중단된 API를 별도로 정의했음. 새 스낵게임 API는 `게임` 탭에서 확인가능)
- 기존 기능을 이식해 게임 종료 시 점수 및 백분율을 알 수 있게 하였음.
- 게임 자체의 메타데이터(id, 게임 이름 등)을 나열하는 API (1-> 사과게임,  2-> 스낵게임)
- 이를 바탕으로 랭킹 조회 등 다른 API과 연계 가능

feat: 세션 종료 시 백분율 및 게임 메타데이터를 포함한다

---

src/main/java/com/snackgame/server/game/snackgame/domain/Snackgame.kt

세션시간을 120초로 조여두었으나, 클라이언트-서버 간 통신 지연에 의해 약간의 오차가 발생할 수 있습니다.
그래서 종종 검증 오류가 발생할 수 있습니다.
세션 종료에 2초의 여유시간을 줍니다.
일단 여유롭게 주었는데, 추후 조정 가능하겠습니다.

feat(snackgame): 세션 당 2초의 스페어 시간을 준다

---

src/main/java/com/snackgame/server/member/domain/Name.java
src/main/java/com/snackgame/server/member/service/DistinctNaming.java
src/main/java/com/snackgame/server/member/service/NameRandomizer.kt
src/main/java/com/snackgame/server/member/service/OidcMemberService.kt
src/test/java/com/snackgame/server/member/domain/NameTest.java
src/test/java/com/snackgame/server/member/service/NameRandomizerTest.kt

랜덤 이름의 길이가 `_` 뒤로 12글자를 생성하였습니다. 하지만 이 과정에서 소셜로그인 시 이름의 길이가 너무 길어져 랭킹에서 사용자의 레벨이 제대로 렌더링 되지 않는 문제가 발생하였습니다.
12글자에서 10글자로 줄여 해결하려합니다.

이름 제약사항 수정

---

src/main/java/com/snackgame/server/member/controller/MemberController.kt
src/main/java/com/snackgame/server/member/service/MemberAccountService.kt
src/main/java/com/snackgame/server/member/service/dto/GroupRequest.kt
src/test/java/com/snackgame/server/member/service/MemberAccountServiceTest.kt

`GroupRequest`에서 유효성 검사를 하여  null을 받을 수 없었습니다.
1. null을 허용하기 위해 검사를 더이상 진행하지 않습니다
2. null일 경우 그룹 탈퇴를 진행합니다.

그룹 탈퇴를 할 수 있다.

---

src/main/java/com/snackgame/server/game/snackgame/biz/controller/SnackgameBizController.kt
src/main/java/com/snackgame/server/game/snackgame/biz/service/SnackgameBizService.kt
src/main/java/com/snackgame/server/game/snackgame/core/controller/SnackgameController.kt
src/main/java/com/snackgame/server/game/snackgame/core/service/SnackgameService.kt

10/14 회의에서 @nijuy 님의 요청이 있었습니다.
기존에는 검증 API의 응답이 두가지 경우로 분리되어 있었습니다.
1. 일반 스낵을 제거했을 경우 `OK`만 반환하였습니다.
2. 황금 스낵을 제거했을 경우 `Created`와 세션에 대한 정보를 반환하였습니다.
스낵의 종류와 무관하게 `Created`와 세션에 대한 정보를 담도록 수정하였습니다.

refactor(snackgame): 게임 검증API의 응답을 통합한다

---

src/main/java/com/snackgame/server/common/exception/Kind.java
src/main/java/com/snackgame/server/messaging/notification/controller/NotificationController.kt
src/main/java/com/snackgame/server/messaging/notification/domain/Device.kt
src/main/java/com/snackgame/server/messaging/notification/domain/DeviceRepository.kt
src/main/java/com/snackgame/server/messaging/notification/exception/DuplicatedDeviceException.kt
src/main/java/com/snackgame/server/messaging/notification/exception/NotificationException.kt
src/main/java/com/snackgame/server/messaging/notification/service/NotificationService.kt
src/main/java/com/snackgame/server/messaging/notification/service/dto/DeviceResponse.kt
src/main/java/com/snackgame/server/messaging/notification/service/dto/DeviceTokenRequest.kt
src/test/java/com/snackgame/server/messaging/notification/controller/NotificationControllerTest.kt
src/test/java/com/snackgame/server/messaging/notification/service/NotificationServiceTest.kt

- #174 의 일부입니다
이 사건은 영국에서 시작되어... (앱 미리보기 업데이트에서 시작했습니다!)
App Store의 경우 앱 미리보기를 업데이트하려면 새 버전 릴리즈가 필요한데요.
쇠뿔도 단김에 빼라고, 새 버전은 사용자에게 도달하기까지 시간이 걸리기 때문에 푸시 메시징도 한 번에 준비하고 있습니다.
문제는 현재 앱에서 식별되는 디바이스 토큰이 그냥 버려지게 된다는 것입니다.
하지만 이걸 미리 모아두면?
푸시 시스템이 완성되었을 때 바로 활용할 수 있다는 장점이 있습니다.
앱에서 디바이스 토큰이 잘 식별되지만, 그냥 버려지게 됨
앱에서 발생하는 디바이스 토큰을 미리 수집해 둠

feat(messaging): 알림 발송을 위해 기기를 등록한다

---

src/main/java/com/snackgame/server/game/metadata/Metadata.kt
src/main/java/com/snackgame/server/game/snackgame/biz/controller/SnackgameBizV2Controller.kt
src/main/java/com/snackgame/server/game/snackgame/biz/domain/SnackgameBizV2.kt
src/main/java/com/snackgame/server/game/snackgame/biz/domain/SnackgameBizV2Repository.kt
src/main/java/com/snackgame/server/game/snackgame/biz/service/SnackgameBizV2Service.kt
src/main/java/com/snackgame/server/game/snackgame/biz/service/dto/SnackgameBizStartResponse.kt
src/main/java/com/snackgame/server/game/snackgame/core/service/dto/SnackgameEndResponse.kt
src/main/java/com/snackgame/server/game/snackgame/core/service/dto/SnackgameResponse.kt
src/main/java/com/snackgame/server/status/StatusService.kt
src/test/java/com/snackgame/server/game/snackgame/biz/domain/SnackgameBizV2Test.kt

- resolves: #185 #188 #186 #187

feat(snackgame.biz): 기존 인증체계를 사용하지 않는다

---

src/main/java/com/snackgame/server/messaging/push/service/dto/NotificationRequest.java
src/main/java/com/snackgame/server/rank/controller/RankingController.kt
src/main/java/com/snackgame/server/rank/event/BestScoreRenewalEvent.java
src/main/java/com/snackgame/server/rank/history/RankHistories.java
src/main/java/com/snackgame/server/rank/history/RankHistory.java
src/main/java/com/snackgame/server/rank/history/RankHistoryRenewal.java
src/main/java/com/snackgame/server/rank/history/RankHistoryService.kt
src/main/java/com/snackgame/server/rank/service/BestScoreRenewal.kt
src/test/java/com/snackgame/server/rank/history/RankHistoriesTest.java
src/test/java/com/snackgame/server/rank/history/RankHistoryRenewalTest.java
src/test/java/com/snackgame/server/rank/history/RankHistoryTest.java
src/test/java/com/snackgame/server/rank/history/fixture/RankHistoryFixture.java

밀려두었던 작업을 한꺼번에 올리느라 양이 꽤 많습니다 미리 죄송합니다 🥲
- resolves: #197 
- resolves: #198 
1. `RankHistory`를 만들어 랭크 전적을 기록할 수 있습니다.
2. 최고 점수 갱신 시 `RankHistory`도 업데이트 될 수 있도록 하였습니다.
3. 랭크 갱신 시 본인이 제친 사용자 5명을 조회할 수 있습니다
- 추가 고민사항
이벤트 발행에 대한 검증은 테스트 하지 않아도 되나..?

feat(RankHistory): 랭크 전적을 기록 및 조회할 수 있다

---

src/main/java/com/snackgame/server/rank/history/RankHistories.java
src/main/java/com/snackgame/server/rank/history/RankHistory.java
src/main/java/com/snackgame/server/rank/history/RankHistoryRenewal.java
src/main/java/com/snackgame/server/rank/history/RankHistoryService.kt
src/test/java/com/snackgame/server/rank/history/RankHistoryServiceTest.java
src/test/java/com/snackgame/server/rank/history/fixture/RankHistoryFixture.java
src/test/java/com/snackgame/server/rank/provoke/ProvokeServiceTest.kt

RankHistories의 `findBelowWithName`에서 limit값을 계산하지 못하는 문제가 발생하여 어플리케이션 레벨에서 계산할 수 있도록 수정하였습니다.

RankHistories의 버그 수정

---

build.gradle.kts

Kotlin-reflect 라이브러리 버전을 찾지 못하는 문제가 있었습니다
Kapt 버전을 1.9.x로 다운그레이드 하여 해결하였습니다

Kapt 버전이 reflect와 호환되도록 버전 수정

---

build.gradle.kts

빌드 도중
`w: Inconsistent JVM-target compatibility detected for tasks 'compileJava' (11) and 'kaptGenerateStubsKotlin' (17).`
이라는 warning message가 생기는 것을 확인하였습니다.
이는 버전이 달라서 Gradle 버전업을 하면 에러가 발생할 수 있다는 것을 알려준 것이므로 나중을 위해 미리 호환성을 맞추었습니다.

JVM-target 호환성을 위한 버전업

---

.github/workflows/dev-deploy.yml

최근들어 자주 그린 어플리케이션을 띄운후 블루 어플리케이션의 프로세스가 종료되지 않아 이후 배포 시에 포트 충돌이 발생하는 경우가 발생하였습니다.
시간을 두어 종료되었는지 확인하고 정상종료 되지 않았다면 강제종료를 시키는 단계를 추가하였습니다

배포시 프로세스가 종료되지 않는 문제 해결

---

src/main/java/com/snackgame/server/game/snackgame/core/domain/item/policy/DailyGrantPolicy.kt
src/test/java/com/snackgame/server/game/snackgame/core/service/ItemServiceTest.kt

아이템 지급 시기가 "이전에 발급 받은 시간으로부터 1일 후" 였습니다.
사용자마다 달라져 혼란이 생길 수 있고 클라이언트와 맞추기 위해 매일 00시 기준 하루가 지나면 발급받을 수 있도록 수정하였습니다.

feat: 아이템은 매일 00시 기준 한번 발급받을 수 있다 (#224)

---

src/main/java/com/snackgame/server/game/session/event/SessionEndEvent.kt
src/main/java/com/snackgame/server/game/session/event/SessionPauseEvent.kt
src/main/java/com/snackgame/server/game/session/event/SessionResumeEvent.kt
src/main/java/com/snackgame/server/game/session/event/SessionStateEvent.kt
src/main/java/com/snackgame/server/game/snackgame/biz/domain/SnackgameBiz.kt
src/main/java/com/snackgame/server/game/snackgame/biz/domain/SnackgameBizV2.kt
src/main/java/com/snackgame/server/game/snackgame/core/domain/Snackgame.kt
src/main/java/com/snackgame/server/game/snackgame/core/domain/item/FeverTime.kt
src/main/java/com/snackgame/server/game/snackgame/core/domain/item/FeverTimeListener.kt
src/main/java/com/snackgame/server/game/snackgame/core/service/SnackgameService.kt
src/main/java/com/snackgame/server/game/snackgame/core/service/dto/StreaksRequest.kt
src/test/java/com/snackgame/server/game/snackgame/core/service/SnackgameServiceTest.kt

- 세션을 일시정지 하여도 피버타임 카운터는 지속되어 적용되지 않는 문제가 있었습니다
- 세션 일시 정지 시 이벤트를 통하여 피버타임도 일시정지 할 수 있습니다.

세션 일시정지시 피버타임을 멈추지 못하던 문제 해결
